/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rita;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author Arvid Persson
 */
public class rita_cirklar_JPanel extends javax.swing.JPanel {
        int plus = 0;
        String vänd;
    /**
     * Creates new form rita_cirklar_JPanel
     */
    public rita_cirklar_JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_snurr = new javax.swing.JButton();

        button_snurr.setText("SNURR");
        button_snurr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_snurrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(button_snurr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(button_snurr, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_snurrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_snurrActionPerformed
        plus++;
    if (plus%2==1){
        vänd = "hel";
        }
    else {
        vänd = "halv";
        }
    repaint();
    }//GEN-LAST:event_button_snurrActionPerformed
public void paintComponent(Graphics g) {
    
    super.paintComponent(g);
        if(vänd.equals("hel")){
            g.fillOval(190, 130, 20, 40);
            g.fillOval(190, 130, 40, 20);
            
        }
        else {
            g.fillOval(190, 130, 40, 20);
            g.fillOval(190, 130, 20, 40);
            
        }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_snurr;
    // End of variables declaration//GEN-END:variables
}
