/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sort;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanel_sort extends javax.swing.JPanel {
    
       private int[] lista;

    /**
     * Creates new form JPanel_sort
     */
    public JPanel_sort() {
        lista = new int[5];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sort = new javax.swing.JButton();
        tf_tal1 = new javax.swing.JTextField();
        tf_tal2 = new javax.swing.JTextField();
        tf_tal3 = new javax.swing.JTextField();
        tf_tal4 = new javax.swing.JTextField();
        tf_tal5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        btn_sort.setText("Sortera");
        btn_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sortActionPerformed(evt);
            }
        });

        jLabel1.setText("Tal 1");

        jLabel2.setText("Tal 2");

        jLabel3.setText("Tal 3");

        jLabel4.setText("Tal 5");

        jLabel5.setText("Tal 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_sort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_tal5)
                    .addComponent(tf_tal4)
                    .addComponent(tf_tal3)
                    .addComponent(tf_tal2)
                    .addComponent(tf_tal1))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tal1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tal2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tal3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tal4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tal5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btn_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sortActionPerformed
    lista[0] = Integer.valueOf(tf_tal1.getText());
    lista[1] = Integer.valueOf(tf_tal2.getText());
    lista[2] = Integer.valueOf(tf_tal3.getText());
    lista[3] = Integer.valueOf(tf_tal4.getText());
    lista[4] = Integer.valueOf(tf_tal5.getText());
    //BubbleSort(lista);
    InfogSort(lista);
    tf_tal1.setText(Integer.toString(lista[0]));
    tf_tal2.setText(Integer.toString(lista[1]));
    tf_tal3.setText(Integer.toString(lista[2]));
    tf_tal4.setText(Integer.toString(lista[3]));
    tf_tal5.setText(Integer.toString(lista[4]));
    }//GEN-LAST:event_btn_sortActionPerformed

    private void BubbleSort(int[] l){
        for(int i = l.length-1; i > 0; i--){
            for(int n = 0; n < i; n++){
                if(l[n] > l[n+1]){
                    int temp = l[n];
                    l[n] = l[n+1];
                    l[n+1] = temp;
                }
            }
        }
    }
    
    private void InfogSort(int[] l){
        
        for(int m  = 1 ; m < l.length ; m++){
            int tmp = l[m];
            int i = m-1;
            
            while(i >= 0 && l[i] < tmp){
                l[i+1] = l[i];
                i--;
            }
            l[i+1] = tmp;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tf_tal1;
    private javax.swing.JTextField tf_tal2;
    private javax.swing.JTextField tf_tal3;
    private javax.swing.JTextField tf_tal4;
    private javax.swing.JTextField tf_tal5;
    // End of variables declaration//GEN-END:variables
}
