/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gissa_formulär;
import java.*;
/**
 *
 * @author Arvid Persson
 */
public class Gissa_formulär extends javax.swing.JFrame {
    int datornsTal;
    int antalGissningar;
    /**
     * Creates new form Gissa_formulär
     */
    public Gissa_formulär() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_header = new javax.swing.JLabel();
        Panel_Speldata = new javax.swing.JPanel();
        ComboBox = new javax.swing.JComboBox();
        Label_Intervall = new javax.swing.JLabel();
        Label_Intervall_0 = new javax.swing.JLabel();
        Label_Speldata = new javax.swing.JLabel();
        button_Start = new javax.swing.JToggleButton();
        button_Igen = new javax.swing.JToggleButton();
        Label_Onödig = new javax.swing.JLabel();
        Panel_Spel = new javax.swing.JPanel();
        txtf_Gissa = new javax.swing.JTextField();
        Label_DatorTal = new javax.swing.JLabel();
        Label_GissaTal = new javax.swing.JLabel();
        txtf_DatorTal = new javax.swing.JTextField();
        button_Gissa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_MinaResultat = new javax.swing.JTextArea();
        Label_MinaResultat = new javax.swing.JLabel();
        txtf_Resultat = new javax.swing.JTextField();
        Label_Spelet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        Label_header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gissa_formulär/Java för ididoter.png"))); // NOI18N

        Panel_Speldata.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20" }));

        Label_Intervall.setText("Intervallen");

        Label_Intervall_0.setText("0 - ");

        javax.swing.GroupLayout Panel_SpeldataLayout = new javax.swing.GroupLayout(Panel_Speldata);
        Panel_Speldata.setLayout(Panel_SpeldataLayout);
        Panel_SpeldataLayout.setHorizontalGroup(
            Panel_SpeldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SpeldataLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Label_Intervall)
                .addGap(39, 39, 39)
                .addComponent(Label_Intervall_0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        Panel_SpeldataLayout.setVerticalGroup(
            Panel_SpeldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SpeldataLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Panel_SpeldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Intervall)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Intervall_0))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        Label_Speldata.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Speldata.setText("Speldata");

        button_Start.setText("Starta Spelet");
        button_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_StartActionPerformed(evt);
            }
        });

        button_Igen.setText("Spela Igen");
        button_Igen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_IgenActionPerformed(evt);
            }
        });

        Label_Onödig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gissa_formulär/Ruta.png"))); // NOI18N

        Panel_Spel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Label_DatorTal.setText("Datorns tal:");

        Label_GissaTal.setText("Gissa ett tal: ");

        txtf_DatorTal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_DatorTalActionPerformed(evt);
            }
        });

        button_Gissa.setText("Gissa");
        button_Gissa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_GissaActionPerformed(evt);
            }
        });

        txta_MinaResultat.setColumns(20);
        txta_MinaResultat.setRows(5);
        jScrollPane1.setViewportView(txta_MinaResultat);

        Label_MinaResultat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_MinaResultat.setText("Mina Resultat");

        javax.swing.GroupLayout Panel_SpelLayout = new javax.swing.GroupLayout(Panel_Spel);
        Panel_Spel.setLayout(Panel_SpelLayout);
        Panel_SpelLayout.setHorizontalGroup(
            Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SpelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_MinaResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(Panel_SpelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_SpelLayout.createSequentialGroup()
                        .addGap(0, 235, Short.MAX_VALUE)
                        .addComponent(button_Gissa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(Panel_SpelLayout.createSequentialGroup()
                        .addGroup(Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_Resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_SpelLayout.createSequentialGroup()
                                .addGroup(Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_DatorTal)
                                    .addComponent(Label_GissaTal))
                                .addGap(23, 23, 23)
                                .addGroup(Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtf_Gissa, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(txtf_DatorTal))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Panel_SpelLayout.setVerticalGroup(
            Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SpelLayout.createSequentialGroup()
                .addGroup(Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_SpelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtf_DatorTal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_DatorTal))
                        .addGap(7, 7, 7)
                        .addComponent(button_Gissa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel_SpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtf_Gissa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_GissaTal))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SpelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_MinaResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txtf_Resultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        Label_Spelet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Spelet.setText("Spelet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Spel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_header)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Panel_Speldata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_Start)
                                    .addComponent(button_Igen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Spelet, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_Speldata, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addComponent(Label_Onödig)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_header, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Label_Onödig)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Label_Speldata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button_Start)
                                .addGap(18, 18, 18)
                                .addComponent(button_Igen)
                                .addGap(16, 16, 16))
                            .addComponent(Panel_Speldata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_Spelet)
                        .addGap(9, 9, 9)))
                .addComponent(Panel_Spel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_StartActionPerformed
    // Skapa datorns tal genom att hämta det största talet från listrutan, 
    // översätt det till ett heltal och skapa ett slumptal som ligger i 
    // intervallet 1 till det största talet. 
    String störstaTal = ComboBox.getSelectedItem().toString();
    int max = Integer.valueOf(störstaTal); 
    java.util.Random slump = new java.util.Random(); 
    datornsTal = slump.nextInt(max) + 1; 
    
    // Avaktivera knappen btnStartaSpe1et och listrutan listMax. 
    button_Start.setEnabled(false); 
    ComboBox.setEnabled(false) ; 
    // Aktivera textrutan txfGissa och knappen btnGissa. 
    txtf_Gissa.setEnabled(true) ; 
    button_Gissa.setEnabled(true) ; 
    
    // Skriv ?? i IblDatornsTa1. 
    txtf_DatorTal.setText( "??");
    // Sätt variablen antalGissningar till e. 
    antalGissningar = 0;
    }//GEN-LAST:event_button_StartActionPerformed

    private void txtf_DatorTalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_DatorTalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_DatorTalActionPerformed

    private void button_GissaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_GissaActionPerformed
    antalGissningar++; 
    String gissa = txtf_Gissa.getText(); 
    int gissatTal = Integer.valueOf( gissa ) ; 
    
    
    if ( gissatTal == datornsTal ){
    txtf_Resultat.setText ( "Korrekt efter "+antalGissningar+" försök.");
    txtf_Gissa.setEnabled( false ); 
    button_Gissa.setEnabled( false ); 
    button_Igen.setEnabled( true ); 
    
    txta_MinaResultat.append( antalGissningar + " försök\n");
    }
    
    else if ( gissatTal < datornsTal ){
    txtf_Resultat.setText( "För lågt. Försök igen.");
    }
    else {
    txtf_Resultat.setText( "För högt. Försök igen." ); 
        }
        // Koden fortsätter med main etc. 
    }//GEN-LAST:event_button_GissaActionPerformed

    private void button_IgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_IgenActionPerformed
    String störstaTal = ComboBox.getSelectedItem().toString();
    int max = Integer.valueOf(störstaTal); 
    java.util.Random slump = new java.util.Random(); 
    datornsTal = slump.nextInt(max) + 1;  
    
    txtf_Gissa.setEnabled(true);
    button_Gissa.setEnabled(true);
    button_Igen.setEnabled(false);
    antalGissningar = 0;
    
    txtf_Gissa.setText(null);
    txtf_Resultat.setText(null);
    txtf_DatorTal.setText( "??");
    
    }//GEN-LAST:event_button_IgenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gissa_formulär.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gissa_formulär.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gissa_formulär.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gissa_formulär.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gissa_formulär().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JLabel Label_DatorTal;
    private javax.swing.JLabel Label_GissaTal;
    private javax.swing.JLabel Label_Intervall;
    private javax.swing.JLabel Label_Intervall_0;
    private javax.swing.JLabel Label_MinaResultat;
    private javax.swing.JLabel Label_Onödig;
    private javax.swing.JLabel Label_Speldata;
    private javax.swing.JLabel Label_Spelet;
    private javax.swing.JLabel Label_header;
    private javax.swing.JPanel Panel_Spel;
    private javax.swing.JPanel Panel_Speldata;
    private javax.swing.JButton button_Gissa;
    private javax.swing.JToggleButton button_Igen;
    private javax.swing.JToggleButton button_Start;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txta_MinaResultat;
    private javax.swing.JTextField txtf_DatorTal;
    private javax.swing.JTextField txtf_Gissa;
    private javax.swing.JTextField txtf_Resultat;
    // End of variables declaration//GEN-END:variables
}
