/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trafikljus;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author Arvid Persson
 */
public class Trafikljus_Jpanel extends javax.swing.JPanel {
    int plus = 0;
    String ljus = "grönt";
    /**
     * Creates new form Trafikljus_Jpanel
     */
    public Trafikljus_Jpanel() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_byt = new javax.swing.JButton();

        btn_byt.setText("Byt");
        btn_byt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bytActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btn_byt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_byt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bytActionPerformed
    plus++;
    if (plus%2==1){
        ljus = "rött";
        }
    else {
        ljus = "grönt";
        }
    repaint();
    }//GEN-LAST:event_btn_bytActionPerformed
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.fillRect(174, 100, 50, 100);
        if(ljus.equals("grönt")){
            g.setColor(Color.red);
            g.fillOval(176, 102, 45, 45);
        }
        else {
            g.setColor(Color.green);
            g.fillOval(176, 152, 45, 45);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_byt;
    // End of variables declaration//GEN-END:variables
}
